spring.application.name=Employee_Details

spring.datasource.url=jdbc:mysql://localhost:3306/mahesh
spring.datasource.username=root
spring.datasource.password=mahesh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9091
int i = 10;
